version: "3"

services:
  runner:
    image: gitea/act_runner
    restart: always
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Gitea 主機與 Action Runner Token
      - GITEA_INSTANCE_URL=http://127.0.0.1:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=TOKEN