version: "3"

networks:
  jenkins:
    external: false

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    container_name: jenkins
    privileged: true
    user: root
    networks:
      - jenkins
    volumes:
      - ./data:/var/jenkins_home
    ports:
      - "4000:8080"